# -*- coding: utf-8 -*-
"""kvecino-practica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/165yMQ6edtdituLaFzZChIiNec88vih0V
"""

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score


dataset = datasets.load_breast_cancer()
#print(dataset)

#Verifico la informacion contenida en el dataset
#print(dataset.keys())

#verifico que datos tiene el dataset
#print(dataset.DESCR)

#Selecciono todas las columnas
x = dataset.data

#Defino los datos de las etiquetas 
y = dataset.target


#Separo los datos entre entrenamiento y prueba 
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.25, random_state = 0)

#Definición del algoritmo a utilizar - distancia euclidiana - k= 5 (marcamos 5 elementos)
algoritmo = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)

#Entreno el algoritmo
algoritmo.fit(x_train, y_train)

#Realizamos una prediccion
y_pred = algoritmo.predict(x_test)

#verifico la matriz de confusion 
m = confusion_matrix(y_test, y_pred)
print("matriz de confusion : ")
print(m)

#calcula la precision del modelo
precision = precision_score(y_test, y_pred)
print("Precision del modelo: ")
print(precision)